name: Build RPM

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## Gleaned from https://yonatankra.com/7-github-actions-tricks-i-wish-i-knew-before-i-started/#6_Saving_Computation_Time_by_Stopping_Obsolete_Workflows
concurrency:
  group: rpmbuild-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install needed RPMs in RHEL container
        if: 'false'
        run: |
          sudo yum install --setopt=tsflags=nodocs -y rpmdevtools rpmlint yum-utils

      - name: Setup rpmbuild tree in RHEL container
        if: 'false'
        run: |
          rpmdev-setuptree
          
      - name: Working directory explore
        run: |
          whoami
          pwd
          ls -lR
